### ISSUE TITLE
[BUG] 1.2.0 opensearch plugin list is located in 1.1.0 section

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/documentation-website#339]
**What is the bug?**
https://opensearch.org/docs/latest/opensearch/install/plugins/
![Screen Shot 2021-12-22 at 1 56 21 PM](https://user-images.githubusercontent.com/65193828/147141686-c0bee4cc-0bd1-4b30-8c91-71b3f188df1d.png)

**How can one reproduce the bug?**

**What is the expected behavior?**

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by keithhc2** [comment]
Fixed with #343

**Comment by peterzhuamazon** [comment]
@keithhc2 it is not fixed as 1.2.0 is consist of both 1.1.0 and 1.2.0 plugins.

**Comment by peterzhuamazon** [comment]
![Screen Shot 2022-01-03 at 2 02 19 PM](https://user-images.githubusercontent.com/65193828/147969156-02819640-9f49-46fb-8c8b-7ff847599fc9.png)

**Comment by keithhc2** [comment]
Should be fixed now.
