### ISSUE TITLE
Error when running `bundle exec jekyll build --future`

### ISSUE THREAD

**Issue by GumpacG** [opensearch-project/documentation-website#6800]
### Description
I will be contributing to this repo however, I'm not able to build the project locally. When try `bundle install` from [CONTRIBUTING.md](https://github.com/opensearch-project/documentation-website/blob/main/CONTRIBUTING.md#setting-up-your-local-copy-of-the-repository) I get this error: 
```
Fetching posix-spawn 0.3.15
Installing posix-spawn 0.3.15 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/guiang/.rvm/gems/ruby-3.2.0/gems/posix-spawn-0.3.15/ext
/Users/guiang/.rvm/rubies/ruby-3.2.0/bin/ruby -I /Users/guiang/.rvm/rubies/ruby-3.2.0/lib/ruby/3.2.0
extconf.rb
creating Makefile

current directory: /Users/guiang/.rvm/gems/ruby-3.2.0/gems/posix-spawn-0.3.15/ext
make DESTDIR\= sitearchdir\=./.gem.20240328-49205-nxi7aq sitelibdir\=./.gem.20240328-49205-nxi7aq clean

current directory: /Users/guiang/.rvm/gems/ruby-3.2.0/gems/posix-spawn-0.3.15/ext
make DESTDIR\= sitearchdir\=./.gem.20240328-49205-nxi7aq sitelibdir\=./.gem.20240328-49205-nxi7aq
compiling posix-spawn.c
posix-spawn.c:226:27: error: incompatible function pointer types passing 'int (VALUE, VALUE,
posix_spawn_file_actions_t *)' (aka 'int (unsigned long, unsigned long, void **)') to parameter of type 'int
(*)(VALUE, VALUE, VALUE)' (aka 'int (*)(unsigned long, unsigned long, unsigned long)')
[-Wincompatible-function-pointer-types]
        rb_hash_foreach(options, posixspawn_file_actions_operations_iter, (VALUE)fops);
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/guiang/.rvm/rubies/ruby-3.2.0/include/ruby-3.2.0/ruby/internal/intern/hash.h:83:40: note: passing
argument to parameter 'func' here
void rb_hash_foreach(VALUE hash, int (*func)(VALUE key, VALUE val, VALUE arg), VALUE arg);
                                       ^
1 error generated.
make: *** [posix-spawn.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/guiang/.rvm/gems/ruby-3.2.0/gems/posix-spawn-0.3.15 for inspection.
Results logged to
/Users/guiang/.rvm/gems/ruby-3.2.0/extensions/arm64-darwin-23/3.2.0/posix-spawn-0.3.15/gem_make.out

An error occurred while installing posix-spawn (0.3.15), and Bundler cannot continue.
Make sure that `gem install posix-spawn -v '0.3.15' --source 'http://rubygems.org/'` succeeds before
bundling.
```

### Environment
macOS Sonoma 14.4
Homebrew 4.2.15
rvm 1.29.12
ruby 3.2.0

### Additional Context
This issue is related to https://github.com/opensearch-project/documentation-website/issues/6242. I've tried suggestions in https://github.com/opensearch-project/documentation-website/issues/6242#issuecomment-1909022045 but I still get the error above. I've also tried ruby versions 2.6 and 2.7 as that worked for me in the past.
I also ran `rvm install 3.2.0 -C --with-openssl-dir=/opt/homebrew/opt/openssl@3.2` instead of the recommended `rvm install 3.2` to resolve this error `Error running '__rvm_make -j10',`.

**Comment by hdhalter** [comment]
Thanks, @GumpacG, for letting us know and for sharing the details and error messages. We will look into this and get back to you asap. We look forward to your contributions!

**Comment by prudhvigodithi** [comment]
I get the same error with package `posix-spawn` on my **mac** as well, should we consider moving to docker based approach so that the environment is constant for all the contributors? @bbarani @peterzhuamazon

**Comment by prudhvigodithi** [comment]
Adding more context I see `posix-spawn` is not actively maintained https://github.com/rtomayko/posix-spawn, hence causing some compatibility issues.

**Comment by peterzhuamazon** [comment]
> I get the same error with package `posix-spawn` on my **mac** as well, should we consider moving to docker based approach so that the environment is constant for all the contributors? @bbarani @peterzhuamazon

I run in my local mac without any issues tho.

**Comment by bbarani** [comment]
I am able to build project-website locally on my mac as well. 

Steps followed:

1. Install [Ruby](https://www.ruby-lang.org/en/) and [Bundler](https://bundler.io/), then run bundle install.
2. Build and start Jekyll with bundle exec jekyll serve.
3. Browse the site at http://127.0.0.1:4000/.


Bundler version: `2.5.6`
Jekyll: `4.3.3`
Ruby: `ruby 3.2.0 (2022-12-25 revision a528908271) [arm64-darwin21]`





<img width="830" alt="Screenshot 2024-03-28 at 10 05 29 AM" src="https://github.com/opensearch-project/documentation-website/assets/70038446/9067df5c-5149-49e2-89cc-4ef97ed2f28d">

**Comment by peterzhuamazon** [comment]
Considering using conda or rvm to lock to specific 3.x version of ruby, and this should be working fine.

**Comment by bbarani** [comment]
Also, can you try installing posix-spawn explicitly using the below command?

`gem install posix-spawn`

**Comment by GumpacG** [comment]
Thanks for all the replies.

> Also, can you try installing posix-spawn explicitly using the below command?
> 
> `gem install posix-spawn`

I still get the same error included in the description of this issue.



> > I get the same error with package `posix-spawn` on my **mac** as well, should we consider moving to docker based approach so that the environment is constant for all the contributors? @bbarani @peterzhuamazon
> 
> I run in my local mac without any issues tho. (intel mac)

Sorry, for more context I am on an M1 mac.

**Comment by prudhvigodithi** [comment]
Hey @GumpacG  yes I'm also using M1 mac and still see the error.
```
Installing posix-spawn 0.3.15 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
```

**Comment by zelinh** [comment]
I'm using Intel core mac and I also got this issue. Tried with ruby 3.3 & 3.2 and both have same error.

**Comment by bbarani** [comment]
@AMoo-Miki Do you have any suggestion? I am able to build the website locally without any issues but some folks are facing issues.

**Comment by hdhalter** [comment]
Here's another similar issue that was resolved: https://github.com/opensearch-project/documentation-website/issues/6242

**Comment by GumpacG** [comment]
> Here's another similar issue that was resolved: #6242

I've tried the suggestions in that ticket and unfortunately, still got the error.

**Comment by GumpacG** [comment]
This worked for me. Thanks all for the help!

**Comment by hdhalter** [comment]
@AMoo-Miki - Any thoughts on this? I don't want this issue to be a barrier to people contributing. Thanks!
