### ISSUE TITLE
[DOC] document download URL for core plugins

### ISSUE THREAD

**Issue by rursprung** [opensearch-project/documentation-website#8763]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.**
in most cases the core plugins can just be installed by running `opensearch-plugin install ${pluginname}`. however, if you're offline you need to have access to the ZIP file of the plugin and accordingly need to download it first.
for plugins hosted in other repositories this is not an issue, as they're (a) published as a github release and (b) usually published to maven central.

currently, the download URL for core plugins is not documented, thus it's not possible to just download them.

**Version:** n/a (all of them)
 
**What other resources are available?**
as discussed on slack with @reta & @saratvemulapalli who can provide the necessary input here

**Comment by rursprung** [comment]
@Naarcha-AWS: please don't assign this to me - _I_ don't know the URL to be documented 😅

**Comment by reta** [comment]
@Naarcha-AWS please assign it to me, thank you!

**Comment by reta** [comment]
> i guess it's always `https://artifacts.opensearch.org/releases/plugins/${PLUGIN}/${OS_VERSION}/${PLUGIN}-${OS_VERSION}.zip`?

@rursprung I am waiting till https://github.com/opensearch-project/opensearch-build/issues/5188 is resolved so we would ensure no changes in the SNAPSHOT repo coordinates.

**Comment by rursprung** [comment]
i just realised that this issue is still assigned to me. that's wrong, please unassign it (or assign it to @reta based on his previous comment). thanks!
